#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true


#bspc rule -a Gimp-2.8 desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Main.py state=floating follow=on focus=on
bspc rule -a Screenkey manage=off

# Startup Polybar
$HOME/.config/polybar/launch.sh
