#!/bin/bash

####################################################
# CREATION     : 2016-11-19
# MODIFICATION : 2016-11-19

# I3block's blocklet which:
# - Shows current coinbase bitcoin price in USD

# Requirements:
# - curl
#
####################################################


case $BLOCK_BUTTON in
    1) nohup xdg-open https://www.gdax.com/trade/BTC-USD &>/dev/null & ;;     # left click
    #2) pkill -RTMIN+2 i3blocks;;    # middle click
esac

#data=$(curl --silent "https://bitcoincharts.com" | grep coinbaseUSD -A 2 | tail -n 1 | awk '{print$2}' | grep -o -E "[[:digit:]]+\.[[:digit:]][[:digit:]]")
#data=$(curl --silent "https://bitcoincharts.com/markets/coinbaseUSD.html" | grep 'Last Trade' | awk '{print$2}' | grep -o -E "[[:digit:]]+\.[[:digit:]][[:digit:]]")
data=$(curl --silent "https://bitcoinwisdom.com/markets/coinbase/btcusd" | grep 'init_price' | awk '{print$3}' | grep -o -E "[[:digit:]]+\.[[:digit:]]+")
echo "$data"
